### ISSUE TITLE
Question version 2.5.0 and GLPI 9.5.7

### ISSUE THREAD

**Issue by phamorais** [yllen/behaviors#11]
Hello Yellen!

I was in doubt about the releases you released.

We are currently on GLPI 9.5.5 and will update to version 9.5.7.

with the Behaviors plugin, we are at version 2.5.0 and we don't use the date format to change the ticket ID.

So, can we continue on GLPI version 9.5.7, and with the Behaviors plugin version 2.5.0?

**Comment by yllen** [comment]
Yes you can
Behaviors plugin version 2.5.0 is also for GLPI 9.5.7.

**Comment by phamorais** [comment]
@yllen 

Thanks.

For those who use version 9.5.5+ and use the issue of changing the ticket ID, which version of the plugin should you go to?
