### ISSUE TITLE
suggestion: add technician when adding followup

### ISSUE THREAD

**Issue by bigben386** [yllen/behaviors#14]
Hi,
Hoping this is the right place to make a feature request. It would be helpful if behaviours could add the actor making a followup to the assigned technicians if they are not already a requester or watcher. This would be similar to the behaviours feature that adds a technician when a solution is provided. This would save us many clicks a day by not having to assign the ticket to ourselves and then switch to the follow-ups page.
Thanks

**Comment by yllen** [comment]
And what do you do if one of technician's groups is already assigned?
You add the technician too? or not?

**Comment by yllen** [comment]
And for private followup?

**Comment by bigben386** [comment]
Honestly we don't do a lot of private followups but I would think that private followups would follow the same rules as above:
if the user adding the followup is a member of an assigned group and they have a profile which allows them to view private followups, then no need to add them as an assigned user.
This would ensure they get any future followups whether they are private or not.
