### ISSUE TITLE
Error when trying to activate the plugin

### ISSUE THREAD

**Issue by alexmicontini** [yllen/behaviors#20]
Hi,

When trying to activate the plugin I get the following error:  

Error al crear glpi_plugin_behaviors_configs
- Error durante la consulta a la base de datos: CREATE TABLE `glpi_plugin_behaviors_configs`( `id` int unsigned NOT NULL, `use_requester_item_group` tinyint NOT NULL default '0', `use_requester_user_group` tinyint NOT NULL default '0', `is_ticketsolutiontype_mandatory` tinyint NOT NULL default '0', `is_ticketsolution_mandatory` tinyint NOT NULL default '0', `is_ticketcategory_mandatory` tinyint NOT NULL default '0', `is_ticketcategory_mandatory_on_assign` tinyint NOT NULL default '0', `is_tickettaskcategory_mandatory` tinyint NOT NULL default '0', `is_tickettech_mandatory` tinyint NOT NULL default '0', `is_tickettechgroup_mandatory` tinyint NOT NULL default '0', `is_ticketrealtime_mandatory` tinyint NOT NULL default '0', `is_ticketlocation_mandatory` tinyint NOT NULL default '0', `is_requester_mandatory` tinyint NOT NULL default '0', `is_ticketdate_locked` tinyint NOT NULL default '0', `use_assign_user_group` tinyint NOT NULL default '0', `use_assign_user_group_update` tinyint NOT NULL default '0', `ticketsolved_updatetech` tinyint NOT NULL default '0', `tickets_id_format` VARCHAR(15) NULL, `changes_id_format` VARCHAR(15) NULL, `is_problemsolutiontype_mandatory` tinyint NOT NULL default '0', `remove_from_ocs` tinyint NOT NULL default '0', `add_notif` tinyint NOT NULL default '0', `use_lock` tinyint NOT NULL default '0', `single_tech_mode` int unsigned NOT NULL default '0', `myasset` tinyint NOT NULL default '0', `groupasset` tinyint NOT NULL default '0', `clone` tinyint NOT NULL default '0', `addfup_updatetech` tinyint NOT NULL default '0', `is_tickettasktodo` tinyint NOT NULL default '0', `is_problemtasktodo` tinyint NOT NULL default '0', `is_changetasktodo` tinyint NOT NULL default '0', `date_mod` timestamp default NULL, `comment` text, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC - Error Invalid default value for 'date_mod'

Glpi: 10.0.1
php:8.1

All the best

**Comment by alexmicontini** [comment]
Hi,

in inc/config.class.php I had to change:

__`date_mod` timestamp default NULL,_

by

_`date_mod` timestamp NULL default NULL,_

and solved the problem.

Cheers

**Comment by yllen** [comment]
Duplicate #19
