### ISSUE TITLE
Error creating tickets

### ISSUE THREAD

**Issue by alexmicontini** [yllen/behaviors#26]
Hello,

When I go to create a ticket I get the following error.

_Uncaught Exception TypeError: in_array(): Argument #2 ($haystack) must be of type array, int given in /var/www/html/glpi/src/RuleTicketCollection.php at line 144_

Glpi: 10.0.1
PHP: 8.1

If I deactivate the plugin there are no problems creating the tickets.

Cheers

**Comment by Tony710** [comment]
Same problem for me

**Comment by yllen** [comment]
which parameters are activated in the plugin?

**Comment by yllen** [comment]
Tested all parameters for creating ticket of Behaviors and i can't reproduce.
Have you some rules based on actors (requester observer or technician)?

**Comment by alexmicontini** [comment]
Hi,

I don't have any active parameters in the plugin or rules based on actors.

**Comment by yllen** [comment]
i can't reproduce.
I can create a ticket with the plugin activated.
The error you indicate corresponds to the business rules.
Can you make test with theses rules disabled?

**Comment by alexmicontini** [comment]
Hello,

after upgrading to GLPI 10.0.2 version no problem with plugin activated.

Thank you so much
