### ISSUE TITLE
Problem to clone profile

### ISSUE THREAD

**Issue by wc55** [yllen/behaviors#27]
The option to clone profile is not appearing in GLPI version 10.0.1. Another friend with the same version has the same problem.

![image](https://user-images.githubusercontent.com/106084399/175575710-04a4455d-a0b3-4613-b95a-20fb9c24ad39.png)

The option to clone is enabled in the plugin. The options "In the active entity" or "in the items's entity" have the same problem.

**Comment by yllen** [comment]
can you confirm the solve of this issue?

**Comment by yllen** [comment]
> I have the same problem, where do I find 2.7.2 version?

Version not yet published, but you have the correction https://github.com/yllen/behaviors/commit/965ca0855393569f753e40fe9d94271df29afd62
