### ISSUE TITLE
Solution type needs to solve ticket

### ISSUE THREAD

**Issue by Tony710** [yllen/behaviors#29]
I have set the option to enforce the solution type when a ticket is solve
![image](https://user-images.githubusercontent.com/78087722/175990809-8e1a83ef-00e5-4a1e-99eb-996cda193e34.png)
But it stay possible to solve ticket without solution type.

**Comment by yllen** [comment]
can you confirme the solve of this issue?

**Comment by Tony710** [comment]
I confirme this change solve the issue.
But I could be fine to add a warning notice in the same way of 'mandatory technician' before saving ticket.
![image](https://user-images.githubusercontent.com/78087722/177930950-eccf8fa8-4d21-4ad1-9e63-b35a4481a432.png)

**Comment by yllen** [comment]
This is not possible to do because I will only have the information of the solution's type once you have validated the resolution form.

**Comment by yllen** [comment]
I have find a solution to display the wanted message
