### ISSUE TITLE
[Bug] "Type of solution is mandatory before ticket is solved/closed" does not work

### ISSUE THREAD

**Issue by jsamaniegog** [yllen/behaviors#32]
GLPI 10.0.2
Behaviors 2.7.1

"Type of solution is mandatory before ticket is solved/closed" does not work because the field is blank (it looks like a GLPI bug).

![image](https://user-images.githubusercontent.com/15769828/178714959-72da415f-d673-4230-8313-5553ddb5d936.png)

**Comment by yllen** [comment]
You must create, in GLPI, type of solution if you want to use this parameter in Behaviors

**Comment by jsamaniegog** [comment]
The problem is that the default element selected is not "-----". It's a GLPI bug, but you should check this in the plugin.

![image](https://user-images.githubusercontent.com/15769828/178935559-099417b6-e4da-4ef3-9cb1-be000fe7e1bd.png)

**Comment by yllen** [comment]
If the selected element is not "---", you have choose a type of solution.
I can't check all items of GLPI. Create a new issue in GLPI's github
