### ISSUE TITLE
Add the first group at ticket creation GLPI 10.0.2

### ISSUE THREAD

**Issue by kbn53** [yllen/behaviors#33]
Hi !

Yesterday, my GLPI was on GLPI 10.0.0 and the Behavior fonction "Take the first asking group" worked.

Today, I update to GLPI 10.0.2 and this fonction is always enable, but when I create a ticket, there is no group added.

Do you see any bug or just anything on my server ?

Thx

**Comment by yllen** [comment]
You have a fix for that https://github.com/yllen/behaviors/commit/c698c5c3b9b4c4b3a5e807e10396d1b09ad779d5
