### ISSUE TITLE
[BUG] Not allowing to clone profiles in GLPI 10.0.2 with Behaviors 2.7.1

### ISSUE THREAD

**Issue by halexsandro** [yllen/behaviors#37]
The Clone tab does not appear after enabling the functionality and the Mass Actions button also does not display the clone function as an option.

![image](https://user-images.githubusercontent.com/15972393/182046296-9563e049-b469-4e31-ab88-1ab6809b480d.png)

**Comment by yllen** [comment]
You have a clone tab in the object you want to clone like indicated in the documentation: https://github.com/yllen/behaviors/wiki/Configuration-guide
You don't have massive actions for cloning with Behaviors.

Clone in massive actions is created by the core and GLPI doesn't allow cloning of profile.
