### ISSUE TITLE
Invalide ticket format number

### ISSUE THREAD

**Issue by sonbinome** [yllen/behaviors#4]
Hello

You offer the possibility to use format number YYMMDD0000 but in January 2022, this format will doesn't working.
ID ticket use a 32bits integer and max value is 2 147 483 647. So January 1st 2022 ID will be 2201010000. Tickets cannot be create with this ID.
I don't think what is possible to use a 64bits integer (GLPI source code need to be rewrite). But can you delete this offer in next version ?

Have a good day

PS : Sorry for my bad English

**Comment by sdbluis** [comment]
Hello dears,

We are suffering from the same problem since today 01/01/2022, is there anything we can do to solve the problem?

**Comment by phamorais** [comment]
Hi @yllen same problem here. :(
In 01/01/2022 we have a error because a format of tickets

![image](https://user-images.githubusercontent.com/35368369/147890621-64a64257-6e50-4ff2-8037-21803a7fac5b.png)

**Comment by keha35** [comment]
Hi, we encounter th same problem and temporary fix it with some alter tables (everywhere in the db where it references to tickets_id) : 
ALTER TABLE `glpi_alerts` CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_changes_tickets` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_documents_items` CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_groups_tickets` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_items_tickets` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_itilfollowups` CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_itilsolutions` CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_logs` CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_notepads` CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_problems_tickets` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_projecttasks_tickets` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_queuednotifications` CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_tickets_tickets` CHANGE `tickets_id_1` `tickets_id_1` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_tickets_tickets` CHANGE `tickets_id_2` `tickets_id_2` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_tickets_users` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_ticketsatisfactions` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_tickettasks` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;
ALTER TABLE `glpi_ticketvalidations` CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;

ALTER TABLE `glpi_events` CHANGE `items_id` `items_id` **BIGINT(11)** NOT NULL;
ALTER TABLE `glpi_tickets` CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;

And you need to do the same if you use plugins where tickets_id is saved.

**Comment by keha35** [comment]
J'ai réalisé un script pour fix rapidement toutes les tables (a placer dans le dossier scripts de GLPI) :

`<?php

if (!defined('GLPI_ROOT')) {
   define('GLPI_ROOT', realpath('../'));
}

include('../inc/includes.php');
include_once(GLPI_ROOT . "/inc/based_config.php");
include_once(GLPI_ROOT . "/inc/db.function.php");
include_once(GLPI_CONFIG_DIR . "/config_db.php");


// To prevent problem of execution time
ini_set("max_execution_time", "0");
ini_set("memory_limit", "-1");
ini_set("display_errors", false);

$GLPI_CACHE = Config::getCache('cache_db');
$GLPI_CACHE->clear(); // Force cache cleaning to prevent usage of outdated cache data

$translation_cache = Config::getCache('cache_trans');
$translation_cache->clear(); // Force cache cleaning to prevent usage of outdated cache data

Config::detectRootDoc();

$GLPI = new GLPI();
$GLPI->initLogger();
$return = [];

$DB = new DB();

$result = $DB->listTables();
foreach ($result as $table) {
   if ($DB->FieldExists($table['TABLE_NAME'], 'tickets_id')) {
         $query = "ALTER TABLE ".$table['TABLE_NAME'] ." CHANGE `tickets_id` `tickets_id` INT(11) UNSIGNED NOT NULL;";
         $DB->queryOrDie($query);
   }
   if ($DB->FieldExists($table['TABLE_NAME'], 'items_id')) {
         if($table['TABLE_NAME'] == 'glpi_events'){
            $query = "ALTER TABLE glpi_events CHANGE `items_id` `items_id` BIGINT(11) NOT NULL";
         } else{
            $query = "ALTER TABLE ".$table['TABLE_NAME'] ." CHANGE `items_id` `items_id` INT(11) UNSIGNED NOT NULL;";
         }
         $DB->queryOrDie($query);
   }
   if ($table['TABLE_NAME'] == 'glpi_tickets') {
         $query = "ALTER TABLE `glpi_tickets` CHANGE `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;";
         $DB->queryOrDie($query);
   }
}`

Si vous avez des clé étrangères du champ glpi_tickets.id, il faudra les supprimer sinon la dernière commande du script ne fonctionnera pas et donc vous aurez toujours le problème de création de tickets.

**Comment by sonbinome** [comment]
Voici le script que j'ai récupéré de notre équipe de devs. Il change pour tous les tickets, la nomenclature YYMMDDxxxx vers YYYYMMxxxx.

ATTENTION, ils ont oublié la table des suivis, donc pensé à l'ajouter et pour les historiques, nous avons volontairement commenter le bloc car cela trop de temps. Nous n'avons plus d'historique sur les tickets mais tout semble être fonctionnel.
N'oubliez pas à la fin de mettre à jour votre "lastincrementnumber" (je crois que c'est un truc comme ça).

`<pre>
<?php
    
/// fonction de connexion a la BDD : renvoi FALSE si echoue
function Connexion_BDD(){


    $host_bdd = "192.168.0.1";
    $user_bdd = "user";
    $pwd_bdd ="password";
    $name_bdd = "glpi";
    $port_bdd = 3306;

    $dsn = "mysql:dbname=" . $name_bdd. ";host=" . $host_bdd . ";port= " . $port_bdd . ";charset=UTF8;";  
    try{
        $cnx_bdd = new PDO($dsn, $user_bdd, $pwd_bdd, array(PDO::MYSQL_ATTR_FOUND_ROWS => true));
    } catch (Exception $ex) {
        return FALSE;
    }
    
    return $cnx_bdd;
}

$cnx_bdd = Connexion_BDD();
$arrayExclude = array("2019","2020","2021", "2022");

$mois = "";
$tt = 0;
$id_increm = 1; //initialisation de l'id a incrementer (AAAAMM'XXXX')
$max_caract = 8;
$debut = time();
if($cnx_bdd && $cnx_bdd_intranet){
    //recuperer les tickets glpi a modifier 
    $req_tickets = "SELECT id FROM glpi_tickets ORDER BY id ASC;";

    $statement = $cnx_bdd->prepare($req_tickets);
    $statement->execute();
    $array = $statement->fetchAll(PDO::FETCH_CLASS);
    $statement->closeCursor();

    //parcourir les liaisons 
    foreach ($array as $key => $ticket) {
        $t1 = time();
        //debut d'un transaction sql dans le cas des tests pour éviter de modifier a l'instant T, quand on gère toutes les modifs de table pour 1 ticket, on commit les modifs.
        $cnx_bdd->beginTransaction();
        $cnx_bdd->query('SET foreign_key_checks = 0'); //permet d'eviter les contraintes de clés etrangeres

        //Si le ticket n'a pas encore été traité par la moulinette (sécurité)
        if(!in_array(substr($ticket->id, 0, 4), $arrayExclude)){
            
            $annee = substr($ticket->id, 0, 2).substr($ticket->id, 2, 2);
            //calcul du nouvel id : 
            $nouvel_id = "20".$annee;
            if($nouvel_id != $mois){ // dans le cas ou le mois a changé, on reinitialise le compteur pour recommencer en AAAAMMXXX1
                $id_increm = 1;
                $mois = $nouvel_id;
            }

            $zero = "";
            for($i = 4; $i < $max_caract-(strlen((string)$id_increm));$i++){//remplissage des 0 pour qu'on ait une fin d'id en 4 digits (ex : si l'id est 4 => ca fera 0004)
                $zero .="0";
            }
        
            $id_final = $nouvel_id.$zero.$id_increm; //construction finale de l'id 

            //maj de la table tickets
            $sqlup = "UPDATE glpi_tickets SET id = :new_id WHERE id = :old_id;";
            $statement_update = $cnx_bdd->prepare($sqlup);
            $statement_update->bindParam("new_id", $id_final);
            $statement_update->bindParam("old_id", $ticket->id);

            $statement_update->execute();
            $res = $statement_update->rowCount();
            $erreur = $statement_update->errorInfo();
            if($erreur[2] != null){
                echo "Mise a jour de la table glpi_tickets : ".$res.", pour le ticket ".$ticket->id."-".$id_final." \n";
                var_dump($erreur);
                echo "\n";
            }

            $arraySQL = array( //talbeau des updates générique qui demande de changer un meme champ
                "glpi_items_tickets",
                "glpi_plugin_satisfaction_reminders", //attention plugin
                "glpi_suppliers_tickets",
                "glpi_olalevels_tickets",
                "glpi_groups_tickets",
                "glpi_changes_tickets", 
                "glpi_plugin_moreticket_waitingtickets", //atttention plugin
                "glpi_plugin_moreticket_urgencytickets", //atttention plugin
                "glpi_slalevels_tickets", 
                "glpi_tickettasks", 
                "glpi_documents", 
                "glpi_problems_tickets", 
                "glpi_tickets_users", 
                "glpi_plugin_moreticket_closetickets", //atttention plugin
                "glpi_ticketsatisfactions", 
                "glpi_projecttasks_tickets",
                "glpi_ticketvalidations",
                "glpi_ticketcosts",
            );
            //preparation des updates générique a faire
            foreach ($arraySQL as $cle => $table) { 
                $sqlup = "UPDATE ".$table." SET tickets_id = :new_id WHERE tickets_id = :old_id;";
                $statement_update = $cnx_bdd->prepare($sqlup);
                $statement_update->bindParam("new_id", $id_final);
                $statement_update->bindParam("old_id", $ticket->id);

                $statement_update->execute();
                $res = $statement_update->rowCount();
                $erreur = $statement_update->errorInfo();
                if($erreur[2] != null){
                    echo "Mise a jour de la table ".$table. " : ".$res.", pour le ticket ".$ticket->id."-".$id_final." \n";
                    var_dump($erreur);
                    echo "\n";
                }
            }   
            /**
             * Cas des updates spéciaux
             */

            //maj de la table ticket_tickets  
            $sqlup = "UPDATE glpi_tickets_tickets SET tickets_id_1 = :new_id WHERE tickets_id_1 = :old_id;";
            $statement_update = $cnx_bdd->prepare($sqlup);
            $statement_update->bindParam("new_id", $id_final);
            $statement_update->bindParam("old_id", $ticket->id);

            $statement_update->execute();
            $res = $statement_update->rowCount();
            $erreur = $statement_update->errorInfo();
            if($erreur[2] != null){
                echo "Mise a jour de la table glpi_tickets_tickets_1 : ".$res.", pour le ticket ".$ticket->id."-".$id_final." \n";
                var_dump($erreur);
                echo "\n";
            }

            $sqlup = "UPDATE glpi_tickets_tickets SET tickets_id_2 = :new_id WHERE tickets_id_2 = :old_id;";
            $statement_update = $cnx_bdd->prepare($sqlup);
            $statement_update->bindParam("new_id", $id_final);
            $statement_update->bindParam("old_id", $ticket->id);

            $statement_update->execute();
            $res = $statement_update->rowCount();
            $erreur = $statement_update->errorInfo();
            if($erreur[2] != null){
                echo "Mise a jour de la table glpi_tickets_tickets_2 : ".$res.", pour le ticket ".$ticket->id."-".$id_final." \n";
                var_dump($erreur);
                echo "\n";
            }

            
           /* $sqlup = "UPDATE glpi_logs SET items_id = :new_id WHERE items_id = :old_id;";
            $statement_update = $cnx_bdd->prepare($sqlup);
            $statement_update->bindParam("new_id", $id_final);
            $statement_update->bindParam("old_id", $ticket->id);

            $statement_update->execute();
            $res = $statement_update->rowCount();
            $erreur = $statement_update->errorInfo();
            if($erreur[2] != null){
                echo "Mise a jour de la table glpi_logs : ".$res.", pour le ticket ".$ticket->id."-".$id_final." \n";
                var_dump($erreur);
                echo "\n";
            }*/

        }else{
            echo "déja traité \n\n";
        }
                
        $cnx_bdd->query('SET foreign_key_checks = 1'); //on remet la verification des contraintes de clés etrangere au cas ou

        $id_increm ++;

        
        //a decommenter pour faire definitive la modification
        // $cnx_bdd->commit();
        
        //a commenter pour faire la modification définitive, le rollback permet de ne pas push la modif 
        $cnx_bdd->rollBack();
        
        //log pour afficher juste le temps passé et les id de tickets traités (ancien id - nouvel id)
        $tt++;
        $t2 = time();
        echo "temps ecoulé : ".($t2-$debut)." - ".$ticket->id."-".$id_final."\n"; 
    }
    echo "traitement total : ".$tt;
    
}else{
    echo "pb connexion bdd";
}

?>
</pre>`

Désolé pour mes imprécisions, je ne suis pas dev.

**Comment by sonbinome** [comment]
[migration-glpi-2022-only.php.txt](https://github.com/yllen/behaviors/files/7801455/migration-glpi-2022-only.php.txt)

Voici le script de nos devs.
Ils ont oublié la table des suivis donc pensé à l'ajouté.
De plus, ils ont commenté la partie pour la table d'historique car cela mettait trop de temps sinon.
Après avoir exécuté le script, il faut penser à modifier la valeur "lastindex" ou un truc du genre, afin que GLPI reprenne bien le compteur au dernier ticket.
Désolé je ne suis pas dev, je ne suis donc pas tjrs hyper précis.

**Comment by FrBillyD** [comment]
Bonjour, 👋

Comme beaucoup, nous avons eu le même problème mais cette fois sur notre ancienne version GLPI (v9.1.3).

J'ai codé un petit script pour récupérer les tables qui contiennent des colonnes "tickets_id" :

```bash
#!/bin/bash
set +H #Gestion des points d’exclamation et autres dans les "echo"
SERVER=`hostname`                                                               #Nom du serveur
CURRENT_DIR=`pwd`                                                               #Répertoire courant
WEB_DIR="/var/www/glpi"                                        #Répertoire de l'installation GLPI

# Configuration de GLPI
DB_HOST=`grep dbhost $WEB_DIR/config/config_db.php | cut -d\' -f2`
DB_NAME=`grep dbdefault $WEB_DIR/config/config_db.php | cut -d\' -f2`
DB_USER=`grep dbuser $WEB_DIR/config/config_db.php | cut -d\' -f2`
DB_PASS=`grep dbpassword $WEB_DIR/config/config_db.php | cut -d\' -f2`

##################################################
### Scan des tables                            ###
##################################################

DB_CONN_STRING="--host=${DB_HOST} --port=3306 --user=${DB_USER} --password=${DB_PASS} ${DB_NAME}"
ALL_TABLES=$(/usr/bin/mysql ${DB_CONN_STRING} -e 'SHOW TABLES' | awk '{ print $1}' | grep -v '^Tables' )

for table in $ALL_TABLES; do
    table_description=$(/usr/bin/mysql ${DB_CONN_STRING} -e "DESCRIBE ${table};")

    if grep -q "\ttickets_id\s" <<<"$table_description"; then
        printf "ALTER TABLE ${table} CHANGE tickets_id tickets_id INT(11) UNSIGNED NOT NULL;\n"
    fi
done

exit 0
```

C'est pas forcément super propre (code utilisé pour d'autres scripts), mais ça a fait le taff. À noter que les requêtes sont affichées mais doivent être exécutées à la main (pour plus de contrôle).
Il manquait juste la requête suivante qui n'est pas récupérée à cause du nom de colonne pas commun :
```SQL
ALTER TABLE glpi_plugin_formcreator_targettickets_actors CHANGE plugin_formcreator_targettickets_id plugin_formcreator_targettickets_id INT(11) UNSIGNED NOT NULL;
```

En espérant que ça serve à d'autres. 👍

**Comment by yllen** [comment]
Corrected in GLPI: https://github.com/glpi-project/glpi/issues/10262

**Comment by yllen** [comment]
Script from GLPI's team to solve this issue: https://github.com/glpi-project/glpi/pull/10263/

**Comment by yllen** [comment]
yours scripts are not full because since GLPI 9.4, format number can also be used with change

**Comment by JosephLive93** [comment]
>It was just missing the following query that is not retrieved because of the unusual column name:
> 
> ```sql
> ALTER TABLE glpi_plugin_formcreator_targettickets_actors CHANGE plugin_formcreator_targettickets_id plugin_formcreator_targettickets_id INT(11) UNSIGNED NOT NULL;
> ```

Hi, thanks for the help! I'm running Formcreator.. Not sure if this is posing a problem or not, but what do you do with this, or how do you execute it??

Thanks!

**Comment by yllen** [comment]
New versions were published for old versions of GLPI with a script to correct this issue.
Published for GLPI 9.2, 9.3 and 9.4 but i think it's also OK for 9.1 and 9.5

**Comment by FathiBenNasr** [comment]
Hi, I changed all the necessary fields to unsigned, changed the behaviors plugin to number tickets in the YYYYMMXXXX format, dumped the database, renumbred all the tickets in the YYYYMMXXXX format, deleted the old database and recreated it from the modified dump, reimporting everything.
Now, new tickets always start from zéro.

**Comment by felag** [comment]
> Hi, I changed all the necessary fields to unsigned, changed the behaviors plugin to number tickets in the YYYYMMXXXX format, dumped the database, renumbred all the tickets in the YYYYMMXXXX format, deleted the old database and recreated it from the modified dump, reimporting everything. Now, new tickets always start from zéro.

*For the record*: I had same problem until I realize I have forgotten to set glpi_tickets.id colum as auto_increment.  
Look again at last line of [keha35 comment above](https://github.com/yllen/behaviors/issues/4#issuecomment-1003971355): :wink: 
`ALTER TABLE glpi_tickets CHANGE id id INT (11) UNSIGNED  NOT NULL AUTO_INCREMENT;`
