### ISSUE TITLE
Single technician and group

### ISSUE THREAD

**Issue by CarlosCFO** [yllen/behaviors#41]
When I set "no" to the option "single technician and group" I see in my tickets the other option as if my choice was "yes" and I´m not to able set two or more technicians. Is that a bug? Thanks in advance.

GLPi 9.5.7
Behaviors  2.6.0

**Comment by yllen** [comment]
I can't change display of a ticket with my plugin, i can just change action done in the object.
So yes, you see all the options and when you try to add a second actor, the plugin doesn't allow it
