### ISSUE TITLE
2.7.1 et GLPI 10.0.2 : ticket NOK en self_sevice

### ISSUE THREAD

**Issue by Sicoval31** [yllen/behaviors#44]
Bonjour, 
**la V2.7.1 du plugin est indiquée devant être utilisée avec une version 10.0.1 maxi de glpi.**
Cela dit, le plugin reste fonctionnel avec une version 10.0.2 SAUF pour les profils **self_service** où l'affichage du ticket et des suivis est blanc : zero info, suivis, taches, etc ...
Pas de probleme pour les profils utilisant une interface standard

**Comment by yllen** [comment]
Je ne comprends pas, ci l'affichage est totalement blanc, c'est le problème de GLPI.
Le plugin Behaviors ne fait que surcharger les actions faites aux objects et en aucun cas n'agit sur l'affichage

**Comment by Sicoval31** [comment]
Moi non plus. Je viens de le réactiver sur un glpi 10.0.3 et là c'est bon, je vois bien la timeline du ticket avec un profil self_service.
A noter que je suis en mode catalogue de service simplifié

PS : j'avais sur ce serveur la V2.6 qui pose le même problème sur mon glpi 10.0.3, apres MAJ du plugin, en 2.7.1 c'est résolu.
Ne reste plus qu'à pouvoir le télécharger depuis le marketplace ;)

**Comment by yllen** [comment]
Merci du retour. Je clos
