### ISSUE TITLE
Technician systematically added as requester at ticket creation 

### ISSUE THREAD

**Issue by Tony710** [yllen/behaviors#45]
Since the GLPI 10.0.3 update, when creating a ticket from the standard interface, the technician who creates the ticket is systematically added as a requester in the same way as the designated requester.
Tthis issu only occurs when the behaviors plugin 2.7.2 is actived.

**Comment by yllen** [comment]
For requester, corrected with https://github.com/yllen/behaviors/commit/512ef7d7c0e53bb4e18c3cecb4a892e658abc346
