### ISSUE TITLE
Bug Ajout du technicien connecté à l'ajout d'un suivi

### ISSUE THREAD

**Issue by xseth03** [yllen/behaviors#48]
Bonjour,

Je rencontre un bug avec la nouvelle fonctionnalité "Ajout du technicien connecté à l'ajout d'un suivi" sur la version 2.6 pour GLPI 9.5.8.
J'ai par moment des techniciens qui n'ont pas ajouté de suivi, mais qui se retrouve avec des tickets en tant que technicien attribué alors que leur action n'était pas sur le ticket en question.
J'ai même eu le cas d'un demandeur via un formulaire formcreator qui s'est retrouvé technicien attribué d'un ticket qui n'avait rien avoir... Dans l'historique, j'ai pu voir que c'est le cron_mailgate qui a ajouté le demandeur, je ne sais pas trop pourquoi... ?

**Comment by yllen** [comment]
Dans Behaviors, l'ajout du technicien ne peut que faire que lors de l'ajout d'un suivi.

Par contre vous avez plusieurs possibilités pour l'ajout automatique d'un technicien 
- le paramètre dans les préférences de l'utilisateur
- les règles métier
- - les gabarits de ticket
Concernant le cron_mailgate, c'est le collecteur de mail et un ticket ouvert par mail aura toujours l'auteur du mail en tant que demandeur du ticket.
