### ISSUE TITLE
Uncaught Exception Type Error: count (): Argument #1 ($value) must be of type Countable|array, bool given in itilsolution.class.php at line 342

### ISSUE THREAD

**Issue by danicouso** [yllen/behaviors#49]
Hi, I have the following error with version 2.6.0 for GLPI 9.5.9, thanks

Uncaught Exception Type Error: count (): Argument #1 ($value) must be of type Countable|array, bool given in itilsolution.class.php at line 342

![imagen](https://user-images.githubusercontent.com/75984175/193519624-f03153ca-ea4f-4df3-a4de-323e314b8b56.png)

**Comment by yllen** [comment]
Which parameters of Behaviors about solution are activated in your GLPI?
When appeared this message?
Can you post the complete message of files/_logs/php-errors.log?

**Comment by yllen** [comment]
I can't reproduce your actions to have the same elements as your picture

**Comment by yllen** [comment]
No news? i close
