### ISSUE TITLE
[Suggestion]"Block the solving/closing of a the ticket if task do to" extend this option to Problems and Changes

### ISSUE THREAD

**Issue by felipebart10** [yllen/behaviors#5]
The plugin only gives this option to tickets. It would be nice if it gives this option to changes and problems too. Thanks :)

**Comment by yllen** [comment]
It's difficult to delete this option for users using it.
Format of concerned fields is changed in core in GLPI 9.5.7.
For earlier versions (GLPI 9.3, 9.3 and 9.4) i had published releases with a script and a readme to follow

**Comment by felipebart10** [comment]
Hi yllen, I didn't understand your comment, is it related to my Issue? I'm thinking that you might wanted to comment this on another issue involving the int. Nevertheless, I opened a pull request to add this feature I've asked for. Best regards :)

**Comment by yllen** [comment]
You are right.
you shouldn't work when i'm sick

**Comment by yllen** [comment]
Fixed https://github.com/yllen/behaviors/commit/c5fcfcb5a5cc7c0a65a23dc82fba98e405035dd4
         https://github.com/yllen/behaviors/commit/0c17df70a9ec6b80fbcec91404273288522a8f94
