### ISSUE TITLE
Pas de "type de solution" par défaut ?

### ISSUE THREAD

**Issue by micter59** [yllen/behaviors#50]
Bonjour,

Nous rencontrons un souci depuis la mise à jour vers GLPI (10.0.3).
Lors de l'ajout d'une solution à un ticket, si nous ne sélectionnons pas un type de solution (j'ai créé "résolu" et "non résolu"), alors le contenu de la solution est perdu, et un message indique que le type de solution est obligatoire pour clôturer un ticket.
Bien sûr, cela vient du fait que j'ai sélectionné cette option dans les paramètrages du plugin behaviors/comportements.

Mais nous n'avions pas ce problème en GLPI 9.5, le type "résolu" était sélectionné par défaut, de souvenir.

Est-ce qu'il y aurait moyen de paramétrer un type de solution par défaut quelque part ?

Merci d'avance.
Et un grand merci pour ce plugin qui rend depuis des années, un très bon service !

Michaël

**Comment by yllen** [comment]
Je viens de regarder et le comportement est identique dans la dernière version de GLPI 9.5.
C'est le type de tâche qui peut être paramétrable.

Si vous avez déjà un type de solution de définie, le paramètre le rendant obligatoire ne sert à rien.
Je ne peux pas inter-agir avec le coeur n'importe comment et malheureusement je n'ai d'autre solution que de supprimer toute la saisie pour annuler la solution.
Désolée

**Comment by micter59** [comment]
Je viens de tester en désactivant le "type de solution" obligatoire, et le ticket est bien mis au statut "résolu". Mais du coup, je n'ai plus le type de solution. Il manque quand même la possibilité de pouvoir choisir un type de solution par défaut, mais je ne sais pas si ça dépend de ce plugin, ou de glpi core.

**Comment by yllen** [comment]
Si vous mettez un type de solution par défaut à quoi sert le type de solution obligatoire ?
L'utilisateur laissera en majorité le type par défaut.

**Comment by micter59** [comment]
Oui, tout à fait. Mais c'est une autre manière de faire. En fait je cherche à reproduire le comportement précédent de GLPI, où on pouvait - sauf erreur de ma part - clôturer un ticket "non-résolu" ou "résolu". Dans la 10.0, on peut juste ajouter une solution, il n'y a plus cette notion de résolu ou pas résolu.
Du coup, j'ai créé des types de solution "résolu" et "non-résolu", mais cela porte à confusion avec le statut "Résolu". Je me dis qu'en mettant une solution "ok" par défaut, et en laissant la possibilité de mettre quand même "non-résolu", ça permet de contourner ça.
Peut-être que je cherche trop compliqué...
