### ISSUE TITLE
GLPI 10.0.3 / Behavior 2.7.1

### ISSUE THREAD

**Issue by kbn53** [yllen/behaviors#52]
Bonjour !

Depuis le passage en 10.0.3, le plugin behavior me rajoute à la création d'un ticket, mon groupe + mon utilisateur en demandeur.

Alors que j'ai bien configuré à Non dans le plugin.

J'ai testé de désinstaller le plugin mais rien ne change, d'ailleurs si je désactive le plugin, je n'ai plus mon groupe et mon utilisateur qui sont ajoutés.

Une idée ?

Merci :)

**Comment by yllen** [comment]
Corrigé dans la version 2.7.2 nouvellement publiée
