### ISSUE TITLE
Problem with displaying in RO profiles items from GenericObject with Global Search enabled

### ISSUE THREAD

**Issue by Wolvverine** [yllen/behaviors#53]
After a long investigation, it came out that the problem with displaying in RO profiles items with Global Search enabled , configured in Generic Object is caused by the Behaviours plugin.

Specifically the "Show my assets" setting in it.

More:

https://forum.glpi-project.org/viewtopic.php?pid=496067#p496067

https://github.com/glpi-project/glpi/issues/12571#issuecomment-1236912084

https://github.com/pluginsGLPI/formcreator/issues/2943

The problem that this setting affects not only the self-service profile but also other profiles where only RO permissions are set for selected assets created in GenericObject.

In addition, the assumption that users_id is the owner is far-fetched. here it would be better to let you set which field of type user is responsible for this (from fields that are available in GLPI and provided additionally e.g.: by plugin fields)

Profile rights:

glpi_profilerights

```
name	rights	
appliance	0	
backup	0	
bookmark_public	1	
budget	0	
cable_management	0	
calendar	0	
cartridge	0	
certificate	0	
change	0	
changevalidation	0	
cluster	0	
computer	0	
config	0	
consumable	0	
contact_enterprise	0	
contract	0	
dashboard	0	
database	0	
datacenter	0	
device	0	
devicesimcard_pinpuk	0	
document	0	
domain	0	
dropdown	0	
entity	1	
```

glpi_profiles
```
"interface","is_default","helpdesk_hardware","helpdesk_item_type","ticket_status","comment","problem_status","create_ticket_on_login","tickettemplates_id","changetemplates_id","problemtemplates_id","change_status","managed_domainrecordtypes"
"central","0","0","[]",NULL,,NULL,"0","0","0","0",NULL,"[]"
```

**Comment by Wolvverine** [comment]
As I described in the links above, for a all profiles that has only READ set for added assets (standard interface) there is a tightening of the SQL in WHERE when the asset has selected the use of "Global Search" :

    (
        `glpi_plugin_genericobject_someitemtables`.`users_id` = xx
    ) AND

Which results in items not being displayed.

**Comment by yllen** [comment]
_"According to the description of the option, this behavior was supposed to apply to the Self-signed profile and not to every profile with only RO."_
I'm not agree with you, it's for all profiles without technician one.

For me it's a bug of genericobject. So open a bug on the GLPI forum part plugin with the name of the plugin in title

**Comment by Wolvverine** [comment]
Two months ago I posted:

https://forum.glpi-project.org/viewtopic.php?id=284683

https://forum.glpi-project.org/viewtopic.php?id=284977

**Comment by yllen** [comment]
Can you post me names of itemtype generated by your plugin genericobject?
table glpi_plugin_genericobject_types
column itemtype

**Comment by Wolvverine** [comment]
in Attachment:
[glpi_plugin_genericobject_types.csv](https://github.com/yllen/behaviors/files/10121737/glpi_plugin_genericobject_types.csv)
