### ISSUE TITLE
Automatically add ticket creator as requester (GLPI 10.0.3)

### ISSUE THREAD

**Issue by rpalmeiro** [yllen/behaviors#54]
Hello,

It seems that when add a ticket manually (standard interface), the creator (i.e. technician or super-admin users) is added to requester field.

With plugin disabled this not occurs. The parameter to add automatically the user as requester is set as "NO".

GLPI - 10.0.3
Behaviors - 2.7.1

Thanks in advance!

**Comment by kbn53** [comment]
Hi ! I've the same issue :)

Same version

**Comment by yllen** [comment]
Corrected https://github.com/yllen/behaviors/commit/512ef7d7c0e53bb4e18c3cecb4a892e658abc346

**Comment by yllen** [comment]
Corrigé dans la version 2.7.2 nouvellement publiée

**Comment by rpalmeiro** [comment]
Perfect yllen! Thks
Best Regards

**Comment by yllen** [comment]
Thanks for news.
