### ISSUE TITLE
Way to to have and view on my items (computers, monitors, ...) in simple interface.

### ISSUE THREAD

**Issue by Tony710** [yllen/behaviors#57]
With Behaviors Puligin, I can allow users to have a vue on there owned items and items owned by there groups, but I need setup there profils to use standard interface instead of simplified Interface.

Is there a solution to allow users to see  assigned equipments to them in the simplified interface?

The problem is that some functions are only available in the simplified interface. 
Example: Glpi Inventory plugin : self-service deployment

**Comment by yllen** [comment]
There is no filter for interface.
I use right of the core and i check only if you doesn't have right to update the item.

The simplified interface doesn't have right to see items, like computer.
I can't change all rights management of the core
