### ISSUE TITLE
Assigning a technician when performing any action on a ticket

### ISSUE THREAD

**Issue by Bosnic** [yllen/behaviors#58]
Hello, good morning.
The GLPI is in version 9.5.9 and the Behaviors plugin is in version 2.5.0. The versions after this one, which are allowed for the mentioned GLPI version, are presenting a conflict with the Escalade plugin.
The Behaviors plugin has the option to assign the technician when resolving the ticket, but is assigning when performing any action on the ticket, is it possible to be assigning only when resolving the ticket?

Evidence:
![Evidence](https://user-images.githubusercontent.com/82185831/203808525-aee68aee-abed-4fc1-8286-931e9dad889b.png)
As seen in the evidence, when creating a follow-up, I was assigned to the ticket.

**Comment by yllen** [comment]
Tested this day version 2.6.1 for GLPI 9.5

- change urgency => no addition of technician
- add a task         => no addition of technician

Have you try with Escalade plugin deactivate?

**Comment by yllen** [comment]
No news, i close
