### ISSUE TITLE
Pb lors de la resolution du ticket avec deux techiciens affecté prise en charge

### ISSUE THREAD

**Issue by Aurelien5135** [yllen/behaviors#59]
bonjour,

j'utilise glpi 10 et behavior 2.7.2, j'ai activé l'option Ajout du technicien connecté à la résolution/clôture d'un ticket et lorsque 2 techniciens sont affectés sur le ticket, nous ne pouvons pas résoudre le ticket (ajouter une solution). 
La résolution du ticket fonctionne si il n'y a aucun technicien  ou 1 seul technicien, j'ai testé en basculons l'option sur non et avoir 2 techniciens et ça fonctionne.
Merci d'avance de votre retour.

**Comment by yllen** [comment]
Je viens de refaire un test et je ne reproduis pas (ticket avec 2 techniciens et 2 groupes de techniciens).
Mon nom est bien ajouté à la résolution du ticket.

Avez-vous un message d'erreur à l'écran ? dans les logs de glpi ?

**Comment by Aurelien5135** [comment]
environnement tech: glpi 10.0.5 sur windows  2016 avec IIS avec base mysql
au niveau des message à l’écran uniquement erreur 500 et je ne trouve rien dans les logs (inetpub ou glpi\files\_logs)
je vais monter un nouvelle environnement et faire un test

**Comment by yllen** [comment]
Pour l'erreur que vous indiquez, cela est déjà corigé https://github.com/yllen/behaviors/commit/68e70e26e342a16d601cd2bbe240f8d650aaff4f

**Comment by Aurelien5135** [comment]
merci le correctif a fonctionné

**Comment by yllen** [comment]
Merci du retour
