### ISSUE TITLE
Si type de solution n'est pas renseigné: perte de la solution

### ISSUE THREAD

**Issue by ylavaud** [yllen/behaviors#60]
bonjour
sous GLPI 10.0.03 avec plugin behavior 2.7.1.

Type de solution est forcé à obligatoire.
Si un technicien rédige une solution et oublie de choisir un type de solution , il perd sa solution.

Serait t il possible d'avoir un message d'avertissement sans perte de solution

merci

**Comment by yllen** [comment]
Le problème est que dans Behaviors j'intercepte les comportements du coeur.
Donc dans le cas de l'ajout d'une solution, je ne peux savoir que le type n'est pas rempli uniquement à la validation de la solution.
Et la seule option à ce moment est de vider tout ce qui est envoyé au coeur sinon la solution sera créée sans type.
Désolée

**Comment by ylavaud** [comment]
Merci pour votre réponse
cordialement
Yvan

**Comment by ylavaud** [comment]
Il serait peut intéressant intéressant de demander  un pull request  à Teclib afin d'ajouter cette fonctionnalité dans le cœur de l'application?
merci
