### ISSUE TITLE
bug ajout du technicien en tant que demandeur

### ISSUE THREAD

**Issue by ylavaud** [yllen/behaviors#62]
bonjour
glpi version 10.0.3
plugin behavior: 2.7.1

quand un technicien créé un ticket à la place de l'utilisateur, en demandeur il met le nom de l'utilisateur mais quand il sauvegarde le ticket son nom est ajouté en tant que demandeur.
Si on désactive le plugin behavior le problème ne se reproduit pas
merci

**Comment by lazarodjn** [comment]
Au secours, j'ai aussi le problème.

**Comment by yllen** [comment]
Déjà corrigé en version 2.7.2 
https://github.com/yllen/behaviors/commit/512ef7d7c0e53bb4e18c3cecb4a892e658abc346
