### ISSUE TITLE
Unable to add a solution when ToDo ticked

### ISSUE THREAD

**Issue by ArriMa** [yllen/behaviors#63]
If there is a task with ToDo type, when ticked the checkbox to set it as "done", If after that, I add a solution it doesn't recognize that the task is already done.

**Steps To reproduce**

1.     Enter in a ticket
2.     Create a new task with ToDo option
3.     Exit and enter to the same ticket
4.     Tick the Task as complete (tick the checkbox)
5.     Add a Solution

A warning said: You cannot resolve the ticket - You cannot solve/close a ticket with task do to
and the button " + Add" is hidded.

If you refresh the page and add the solution now the button appear.

**Comment by yllen** [comment]
After 4. you must validate the task to save the change

Test doing this day and it's OK if you validate the task

**Comment by ArriMa** [comment]
Hi yllen, could you better explain what you mean with "After 4. you must validate the task to save the change"?
Thanks

**Comment by yllen** [comment]
When you had tick the task to complete, you must validate the task before adding a solution
