### ISSUE TITLE
[GLPI 9.5] Impossible de cloner un ticket

### ISSUE THREAD

**Issue by cyrakuse** [yllen/behaviors#64]
Nous utilisons actuellement GLPI 9.5 avec la version 2.6 du plugin.

Lorsqu'on essaye de cloner un ticket, on obtient une erreur spécifiant que le demandeur est obligatoire.
Or dans les options du plugin, l'option "demandeur obligatoire" est à "non".

**Comment by yllen** [comment]
Déjà corrigé https://github.com/yllen/behaviors/commit/7a81b0dd218140decd15a16fcb1ba3075e356d0d
