### ISSUE TITLE
[GLPI 10.0.5] - Groupe du demandeur non respecté

### ISSUE THREAD

**Issue by kevin39** [yllen/behaviors#65]
Bonjour,
Depuis la MAJ en 10.0.5 le groupe du demandeur lors d'un nouveau ticket n'est plus respecté. Le ticket lui ai directement affecté.
Les tickets arrivent depuis un collecteur.

Bug ou quelque chose m'échappe ?

Merci

**Comment by kevin39** [comment]
Précisions : le paramètre est défini sur "Premier"

![AS -2022-12-23 15 33 50](https://user-images.githubusercontent.com/976058/209352553-ae7b7ee4-a222-4d5f-8c18-508c1948e8c9.png)

**Comment by kevin39** [comment]
Confirmed, patch is working.

Thanks.

**Comment by yllen** [comment]
Thanks for news @kevin39
