### ISSUE TITLE
GLPI 10.0.5 marketplace

### ISSUE THREAD

**Issue by ylavaud** [yllen/behaviors#66]
bonjour

sur GLPI 10.0.5, la dernière version du plugin n'est pas proposée dans le marketplace.
Je suis en Behavior 2.7.1 et il ne me propose pas de mise à jour vers la version 2.7.2
N'ayant pas accès au serveur c'est ma seule possibilité pour mettre à jour.

https://github.com/yllen/behaviors/blob/master/behaviors.xml#L36
dans le xml il est indiqué uniquement pour 10.0.3

merci

**Comment by orthagh** [comment]
@yllen pour la compatibilité, utilise simplement `~10.0.3`, cela implique 10.0.3, 10.0.4, 10.0.5, 10.0.6, etc (mais pas 10.1.0, 10.1.1)
Sauf si tu veux fixer précisement ces versions. on prévoit une 10.0.6 mi janvier, cela voudra dire repasser sur ton xml à ce moment.
