### ISSUE TITLE
Groupe demandeur non assigné au ticket ouvert par le collecteur de mail

### ISSUE THREAD

**Issue by bern2b** [yllen/behaviors#70]
Bonjour,

version glpi : 10.0.6
version beehavior : 2.7.2

Depuis la mise à jour de glpi en 10.0.6 et de behavior en version 2.7.2, le groupe demandeur ne remonte pas si le ticket est issu du collecteur de mail.

l'option "prendre le groupe du demandeur" est paramétrée sur "tous".
Le groupe remonte en revanche bien si le ticket est créé par l'utilisateur pour directement par un technicien.

Nous avons tenté de modifier le fichier ticket.class.php comme indiqué dans l'issues #C65 mais sans effet.

Pourriez-vous nous donner des indications sur ce problème ?

Merci

**Comment by bern2b** [comment]
Bonjour,
désolé de relancer mais le problème est gênant pour le suivi de nos tickets.
Pourriez vous regarder ce qui peut bloquer et si un patch peut être fait ?
Merci d'avance

**Comment by froch29** [comment]
Bonjour,

Même problème pour moi.
Option "prendre le groupe du demandeur" testé avec "tous" et "premier"
GLPI 10.0.6
Le groupe remonte bien à la création manuelle du ticket.

Bonne journée

**Comment by yllen** [comment]
Pouvez-vous me faire un retour concernant ma correction ci-dessus ?

**Comment by bern2b** [comment]
Bonjour @yllen, merci pour le retour.
J'ai testé la modification mais le comportement reste le même.
Les tickets par collecteur ne font pas remonter le groupe demandeur.

**Comment by bern2b** [comment]
OK, pas de problème.
Merci i

**Comment by froch29** [comment]
Je viens de tester en "Premier" et "Tous" mais il n'y a toujours pas de groupe qui remonte.
Je ne trouve rien dans les logs.
Dans quel log pourrait-il y avoir une info ?

**Comment by froch29** [comment]
Ca fonctionne !
J'ai fait la modification dans /glpi/plugins/behaviors et dans glpi/marketplace/behaviors
J'ai pour habitude de mettre les plugins dans "plugins" mais j'ai l'impression que celui ci passe par "marketplace"
Merci pour la correction.

**Comment by bern2b** [comment]
Effectivement, en modifiant dans le dossier marketplace, c'est OK avec la fonction "TOUS" merci @froch29 .

Merci @yllen pour le patch et désolé. Machinalement, je suis allé modifier dans le dossier "plugins" au lieu de "marketplace".

**Comment by yllen** [comment]
Merci du retour, je clos

**Comment by eramos13** [comment]
I applied correction #70. However, there is a problem when the option to allow anonymous tracking (recipient) is enabled. The requester field appears blank when creating the ticket per mail recipient.
