### ISSUE TITLE
Type de solution

### ISSUE THREAD

**Issue by cyrakuse** [yllen/behaviors#80]
Bonjour,

J'ai activé l'option "Type de solution obligatoire pour résoudre/fermer un ticket" mais cela est sans effet. 
Je peux toujours résoudre un ticket sans type de solution.

Glpi v10.0.9
Plugin v2.7.2

**Comment by tdupuydvi** [comment]
Bonjour,
Je suis dans le même cas de figure.
GLPI V10.0.9.
Plugin V2.7.2
Debian V11.7
Cordialement.

**Comment by yllen** [comment]
Correction déjà effectuée https://github.com/yllen/behaviors/issues/69
