### ISSUE TITLE
Does not perform all translations into Spanish

### ISSUE THREAD

**Issue by willysaurio** [yllen/behaviors#82]
Some translations are fine but others continue in English
![image](https://github.com/yllen/behaviors/assets/65296683/7017757e-3c7f-4dbf-b5e5-4062a99a7227)

For example when you do not have a location the ticket and it is resolved / closed the warning is also displayed in English instead of Spanish. The same if you have no category and other restrictions configured in the behavior.
![image](https://github.com/yllen/behaviors/assets/65296683/4a65c4f7-0ac1-4819-b961-56046cebe201)

**Comment by yllen** [comment]
Only 50%% was translated for Spanish. 
You can request to be a translator of this language on Transiflex (https://app.transifex.com/yllen/)
