### ISSUE TITLE
Script from GLPI's team to solve this issue: https://github.com/glpi-project/glpi/pull/10263/

### ISSUE THREAD

**Issue by filipecarolino** [yllen/behaviors#9]
Script from GLPI's team to solve this issue: https://github.com/glpi-project/glpi/pull/10263/

_Originally posted by @yllen in https://github.com/yllen/behaviors/issues/4#issuecomment-1004901546_

Good night!
I saw the file that was changed and the new file that was created.
I added the new lines in the inc/dbmysql.class.php file and created the new inc/console/migration/unsignedkeyscommand.class.php file, then I restarted the server but I still can't generate a new ticket.
My GLPI version is 9.5.1 on a Debian 10. I use the Behavior plugin.
Thanks.

**Comment by JosephLive93** [comment]
Running into the same issue.. Did you happen to find a fix??

**Comment by filipecarolino** [comment]
Hi! I managed to solve it following the guidance of "keha35" in this thread [https://github.com/yllen/behaviors/issues/4](url)

**Comment by yllen** [comment]
You can try the script added in the latest versions published (for old versions of GLPI, but i think it's OK also for 9.5)

**Comment by yllen** [comment]
differents versions with script were publising
