### ISSUE TITLE
Technician assignment when adding follow up does not work when I am part of the technical group that is assigned to the ticket

### ISSUE THREAD

**Issue by vinilamelas** [yllen/behaviors#91]
Technician assignment when adding follow up does not work when I am part of the technical group that is assigned to the ticket

I am part of the group that is assigned to the ticket and I add a new follow-up with the Technician assignment when adding follow up option activated, my user is not automatically assigned

**Comment by laurixia** [comment]
neither do I, I have also requested it in another thread.

**Comment by yllen** [comment]
This comportment is correct to limit number of notification received by an user
If you are member of an assigned group, your name is not added.

**Comment by vinilamelas** [comment]
Hello,
But theoretically, the technician who is adding the follow-up is always part of the technical group and this function makes it easier by not having to reserve himself for the call and then add a follow-up.
Is it not possible to remove this limitation?

**Comment by vinilamelas** [comment]
Any news?
It will be of great help to release the technician's assignment by adding follow-up even if you are part of the technical group that is assigned to the call.

**Comment by laurixia** [comment]
For me it is important because I know which ticket each particular technician is working on because it has been assigned to him/her when writing the follow-up. Otherwise it is assigned to the group that are all but not to the technician who has taken the ticket to treat it.

**Comment by vinilamelas** [comment]
Hello, You can close this request. I found another way to accomplish this action.

**Comment by laurixia** [comment]
can you tell me what solution you have found? it is important for me too.

**Comment by vinilamelas** [comment]
Olá @laurixia 

I used the plugin itself, I just commented the lines below the file /glpi/plugins/behaviors/inc/itilfollowup.class.php and activated the option in the plugin configuration

![image](https://github.com/yllen/behaviors/assets/51828518/6a9696d0-5641-4c1d-b927-2aa8d691c3f2)

**Comment by laurixia** [comment]
@vinilamelas your solution worked perfectly. Eternally gratefull.
