### ISSUE TITLE
[GLPI 10.0.11] Group requester option doesn't work

### ISSUE THREAD

**Issue by tsmr** [yllen/behaviors#92]
Change in GLPI 10.0.11

On static function onNewTicket()

$_POST['id'] doesn't exist so the requester group affectation doesn't work

**Comment by pyero83** [comment]
Idem for me

**Comment by AurelBichop** [comment]
Idem for me

**Comment by yllen** [comment]
try the fix above

**Comment by AurelBichop** [comment]
Great thank you, it works for me

**Comment by yllen** [comment]
OK i close this issue
